### ISSUE TITLE
Error in ./HomePage class HomePage - caused by: File 'Roboto-Regular.ttf' not found in virtual file system

### ISSUE THREAD

**Issue by PrabuGovindan** [calraiden/cal-pdfmake-test#1]
Error: Error in ./HomePage class HomePage - inline template:9:1 caused by: File 'Roboto-Regular.ttf' not found in virtual file system
    at ViewWrappedError.BaseError [as constructor] (http://localhost:8101/build/main.js:7445:34)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:8101/build/main.js:7474:16)
    at new ViewWrappedError (http://localhost:8101/build/main.js:52231:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:8101/build/main.js:97245:23)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:8101/build/main.js:97258:23)
    at HTMLButtonElement.<anonymous> (http://localhost:8101/build/main.js:37015:36)
    at t.invokeTask (http://localhost:8101/build/polyfills.js:3:9723)
    at Object.onInvokeTask (http://localhost:8101/build/main.js:35086:37)
    at t.invokeTask (http://localhost:8101/build/polyfills.js:3:9659)
    at e.runTask (http://localhost:8101/build/polyfills.js:3:7083)

**Comment by kishandonepudi** [comment]
+1
